In [2]:
import pandas as pd

In [4]:
dataset=pd.read_csv('insurance_pre.csv')

In [6]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [8]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder=OrdinalEncoder(categories=[['female','male']])
dataset[['sex']]=ordinal_encoder.fit_transform(dataset[['sex']])

In [10]:
dataset[['sex']]=dataset[['sex']].astype(int)

In [12]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder=OrdinalEncoder(categories=[['yes','no']])
dataset[['smoker']]=ordinal_encoder.fit_transform(dataset[['smoker']])

In [14]:
dataset[['smoker']]=dataset[['smoker']].astype(int)

In [16]:
dataset.head()

   age  sex     bmi  children  smoker      charges
0   19    0  27.900         0       0  16884.92400
1   18    1  33.770         1       1   1725.55230
2   28    1  33.000         3       1   4449.46200
3   33    1  22.705         0       1  21984.47061
4   32    1  28.880         0       1   3866.85520

In [18]:
independent=dataset[['age', 'sex', 'bmi', 'children', 'smoker']]

In [20]:
dependent=dataset[['charges']]

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param={'criterion':['squared_error','friedman_mse','poisson'],
       'max_features':['sqrt','log2'],
       'n_estimators':[50,100,200,250]}

grid=GridSearchCV(RandomForestRegressor(),param,refit=True,verbose=3,n_jobs=-1)

grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\91636\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100, 200, 250]},
             verbose=3)

In [28]:
print(grid.best_params_)

{'criterion': 'friedman_mse', 'max_features': 'sqrt', 'n_estimators': 100}

In [30]:
results=grid.cv_results_

In [35]:
table=pd.DataFrame.from_dict(results)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.267225,0.014209,0.018295,0.004676,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.854315,0.772771,0.849019,0.826136,0.839485,0.828345,0.029392,24
1,0.492378,0.055179,0.024701,0.002383,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859553,0.779619,0.862224,0.826610,0.840870,0.833775,0.030028,13
2,0.887222,0.026138,0.055637,0.021456,squared_error,sqrt,200,"{'criterion': 'squared_error', 'max_features':...",0.856409,0.780721,0.862153,0.828675,0.840299,0.833651,0.028986,14
3,1.063460,0.037612,0.039130,0.003480,squared_error,sqrt,250,"{'criterion': 'squared_error', 'max_features':...",0.857927,0.781779,0.860661,0.829513,0.841541,0.834285,0.028590,11
4,0.236946,0.018078,0.011706,0.001903,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.851314,0.777472,0.863743,0.827413,0.834587,0.830906,0.029582,23
5,0.446664,0.032751,0.019507,0.004244,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.859976,0.776380,0.856785,0.825681,0.839123,0.831589,0.030267,22
6,0.882758,0.069672,0.030500,0.001359,squared_error,log2,200,"{'criterion': 'squared_error', 'max_features':...",0.861421,0.779225,0.863487,0.830613,0.841266,0.835202,0.030590,3
7,1.050142,0.079306,0.037949,0.002119,squared_error,log2,250,"{'criterion': 'squared_error', 'max_features':...",0.861695,0.777337,0.863247,0.828957,0.842664,0.834780,0.031402,4
8,0.224115,0.025483,0.011294,0.000892,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.857245,0.780107,0.859654,0.829095,0.839502,0.833121,0.028821,18
9,0.412661,0.032336,0.020637,0.002130,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859343,0.781281,0.867828,0.826369,0.841532,0.835271,0.030570,1
10,0.785691,0.060783,0.033600,0.003851,friedman_mse,sqrt,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.860536,0.777150,0.858520,0.829270,0.841328,0.833361,0.030369,16
11,1.017749,0.050398,0.040331,0.004754,friedman_mse,sqrt,250,"{'criterion': 'friedman_mse', 'max_features': ...",0.857394,0.778747,0.861109,0.828666,0.840185,0.833220,0.029660,17
12,0.213650,0.009922,0.011833,0.003668,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.861200,0.776495,0.858999,0.822999,0.841019,0.832142,0.031063,20
13,0.432028,0.033650,0.017368,0.001292,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859398,0.781569,0.862367,0.828608,0.840099,0.834408,0.029204,8
14,0.811220,0.085089,0.031633,0.004265,friedman_mse,log2,200,"{'criterion': 'friedman_mse', 'max_features': ...",0.860790,0.779430,0.863738,0.826925,0.840991,0.834375,0.030588,9
15,0.981884,0.031937,0.037738,0.003780,friedman_mse,log2,250,"{'criterion': 'friedman_mse', 'max_features': ...",0.859509,0.779635,0.862912,0.831161,0.839297,0.834503,0.029923,7
16,0.245568,0.020820,0.011381,0.002054,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.856187,0.779309,0.855249,0.829146,0.841525,0.832283,0.028286,19
17,0.445355,0.026091,0.017721,0.000998,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858720,0.782126,0.861987,0.830666,0.842590,0.835218,0.028854,2
18,0.887055,0.060201,0.029419,0.002492,poisson,sqrt,200,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860133,0.781695,0.860239,0.829602,0.841377,0.834609,0.028911,6
19,1.076865,0.090828,0.035693,0.002162,poisson,sqrt,250,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858591,0.781400,0.860207,0.830892,0.840658,0.834349,0.028676,10
20,0.234791,0.019188,0.013049,0.001915,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.858079,0.778665,0.860173,0.825449,0.837840,0.832041,0.029649,21
21,0.467917,0.035045,0.019312,0.001318,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857253,0.783850,0.858776,0.826796,0.846382,0.834611,0.027831,5
22,0.921268,0.063103,0.030702,0.002103,poisson,log2,200,"{'criterion': 'poisson', 'max_features': 'log2...",0.858947,0.783389,0.857547,0.827841,0.841611,0.833867,0.027691,12
23,0.986697,0.079516,0.031761,0.004327,poisson,log2,250,"{'criterion': 'poisson', 'max_features': 'log2...",0.857550,0.779820,0.860984,0.828526,0.841214,0.833619,0.029324,15